# This file is generated by the update_project.py script.
# Manual edits will be overwritten by the next update.

CC=emcc
CFLAGS=-I. -v -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap", "allocate", "intArrayFromString", "stackSave", "stackAlloc", "stackRestore"]' \
       -s EXPORTED_FUNCTIONS='["_main", "_read_text_callback", "_read_image_callback"]' \
	     -fsanitize=undefined \
       --js-library web/taxmanLib.js \
       -I taxman-engine/Engine/Actions/ \
       -I taxman-engine/Engine/Components/ \
       -I taxman-engine/Engine/Logic/ \
       -I taxman-engine/Engine/Math/ \
       -I taxman-engine/Engine/Render/ \
       -I taxman-engine/Engine/Resources/ \
       -I taxman-engine/Engine/Scene/ \
       -I taxman-engine/Engine/Strings/ \
       -I taxman-engine/Engine/Tests/ \
       -I taxman-engine/Engine/Utils/ \
       -I taxman-engine/Tools/Components/ \
       -I taxman-engine/Tools/Physics/ \
       -I taxman-engine/Tools/Tilemap/ \
       -I game/GameData/ \
       -I game/Objects/ \
       -I game/Scenes/ \
       -I platform/ # -D DEBUG

OUT_DIR=docs
OBJ_DIR=obj
SRC_DIR=platform
COPY_DIR=web
ASSETS_DIR=assets

MKDIR_P=mkdir -p
CSRC = $(wildcard taxman-engine/Engine/Actions/*.c) \
       $(wildcard taxman-engine/Engine/Components/*.c) \
       $(wildcard taxman-engine/Engine/Logic/*.c) \
       $(wildcard taxman-engine/Engine/Math/*.c) \
       $(wildcard taxman-engine/Engine/Render/*.c) \
       $(wildcard taxman-engine/Engine/Resources/*.c) \
       $(wildcard taxman-engine/Engine/Scene/*.c) \
       $(wildcard taxman-engine/Engine/Strings/*.c) \
       $(wildcard taxman-engine/Engine/Tests/*.c) \
       $(wildcard taxman-engine/Engine/Utils/*.c) \
       $(wildcard taxman-engine/Tools/Components/*.c) \
       $(wildcard taxman-engine/Tools/Physics/*.c) \
       $(wildcard taxman-engine/Tools/Tilemap/*.c) \
       $(wildcard game/GameData/*.c) \
       $(wildcard game/Objects/*.c) \
       $(wildcard game/Scenes/*.c) \
       $(wildcard platform/*.c)
OBJ = $(CSRC:.c=.o)
COPY_FILES=$(patsubst ${COPY_DIR}/%,${OUT_DIR}/%,$(wildcard ${COPY_DIR}/*))

.PHONY: all clean directories assets

all: directories $(COPY_FILES) game assets

clean:
	rm -rf ${OUT_DIR} ${OBJ_DIR} ${OBJ} *.o

directories: ${OUT_DIR}

assets:
	bash scripts/generate_assets.sh

${OUT_DIR} ${OBJ_DIR}:
	${MKDIR_P} $@

$(OUT_DIR)/button_down.png: $(COPY_DIR)/button_down.png
$(OUT_DIR)/button_up.png: $(COPY_DIR)/button_up.png
$(OUT_DIR)/favicon.ico: $(COPY_DIR)/favicon.ico
$(OUT_DIR)/index.html: $(COPY_DIR)/index.html
$(OUT_DIR)/loader.js: $(COPY_DIR)/loader.js
$(OUT_DIR)/taxman.css: $(COPY_DIR)/taxman.css
$(OUT_DIR)/taxmanLib.js: $(COPY_DIR)/taxmanLib.js

#-include $(OBJ:.o=.d)

$(OUT_DIR)/%:
	cp -f $< $@

game: $(OBJ) $(CSRC) main.o
	$(CC) $(CFLAGS) -o ${OUT_DIR}/core.js $(OBJ) main.o
